services:
  db:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    command: 
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/code
    depends_on:
      - db
    
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; export DJANGO_SETTINGS_MODULE=api_clients.settings; gunicorn -c gunicorn.conf.py api_clients.wsgi:application'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

    depends_on:
      - db
      - migration

  test:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py test' 
    environment:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    depends_on:
      - db
      - migration

volumes:
  pgdata:
