services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    env_file: .env
    command: 
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/code
    depends_on:
      - db
    
  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; export DJANGO_SETTINGS_MODULE=api_clients.settings; gunicorn -c gunicorn.conf.py api_clients.wsgi:application'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

    depends_on:
      - db
      - migration

  test:
    build: .
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py test' 
    depends_on:
      - db
      - migration

volumes:
  pgdata: