# Generated by Django 4.1.6 on 2023-02-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth', models.DateField()),
            ],
        ),
    ]
